title: PNU_3991
lang: en
description: Winter Semester Courses 1399/2020.

remote_theme: rundocs/jekyll-rtd-theme@v2 # rundocs/jekyll-theme-docsify

debug:
  compress: true
  dist: false
  shortcodes: true

direction: rtl

author: alirazavi

addons:
  - github
  - i18n
  - plugins
  - analytics

sass:
  style: compressed

copyright:
  revision: true

readme_index:
  with_frontmatter: true

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-github-metadata


exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec



# also available via file: _data/translate.yml
translate:
  # shortcodes
  danger: خطا
  note: یادداشت
  tip: نکته
  warning: اخطار
  # 404
  not_found: صفحه‌ای پیدا نشد
  # copyright
  revision: بازبینی
  # search
  searching: درحال جستجو
  search: جستجو
  search_docs: جستجو
  search_results: نتایج جستجو
  search_results_found: نتایج جستجو #
  search_results_not_found: هیچ نتیجه‌ای یافت نشد
